[2025-06-11T16:16:29.635+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_marketing_campaigns_eu manual__2025-06-11T16:08:10.701979+00:00 [queued]>
[2025-06-11T16:16:29.645+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_marketing_campaigns_eu manual__2025-06-11T16:08:10.701979+00:00 [queued]>
[2025-06-11T16:16:29.645+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-11T16:16:29.658+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_eu.process_marketing_campaigns_eu> on 2025-06-11 16:08:10.701979+00:00
[2025-06-11T16:16:29.665+0000] {standard_task_runner.py:60} INFO - Started process 37771 to run task
[2025-06-11T16:16:29.667+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_transform_staging_v2', 'process_region_eu.process_marketing_campaigns_eu', 'manual__2025-06-11T16:08:10.701979+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmp0bzrlbx5']
[2025-06-11T16:16:29.669+0000] {standard_task_runner.py:88} INFO - Job 237: Subtask process_region_eu.process_marketing_campaigns_eu
[2025-06-11T16:16:29.724+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_marketing_campaigns_eu manual__2025-06-11T16:08:10.701979+00:00 [running]> on host 5950010ae7c1
[2025-06-11T16:16:29.852+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_transform_staging_v2' AIRFLOW_CTX_TASK_ID='process_region_eu.process_marketing_campaigns_eu' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T16:08:10.701979+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T16:08:10.701979+00:00'
[2025-06-11T16:16:35.148+0000] {logging_mixin.py:188} INFO - Debugggg::::Vector(spark://5950010ae7c1:36763/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar, spark://5950010ae7c1:36763/jars/snowflake-jdbc-3.13.17.jar)
[2025-06-11T16:16:35.148+0000] {logging_mixin.py:188} INFO - Processing marketing_campaigns for region eu
[2025-06-11T16:16:35.166+0000] {logging_mixin.py:188} INFO - /opt/airflow/data/raw/region=eu/table=marketing_campaigns/load_date=2025-06-11
[2025-06-11T16:16:49.746+0000] {logging_mixin.py:188} INFO - Error processing marketing_campaigns for eu: 'Column' object is not callable
[2025-06-11T16:16:51.439+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_dag.py", line 242, in process_table
    df_transformed = transform_func(df_raw, region,exchange_rates)
  File "/opt/airflow/scripts/etl/transform/marketing_campaigns.py", line 95, in transform_marketing_campaigns
    return transform_marketing_campaigns_eu(df, exchange_rates)
  File "/opt/airflow/scripts/etl/transform/marketing_campaigns.py", line 62, in transform_marketing_campaigns_eu
    (col("budget_eur").lit(rate)).alias("budget_usd"),
TypeError: 'Column' object is not callable
[2025-06-11T16:16:51.450+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=multi_region_transform_staging_v2, task_id=process_region_eu.process_marketing_campaigns_eu, execution_date=20250611T160810, start_date=20250611T161629, end_date=20250611T161651
[2025-06-11T16:16:51.460+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 237 for task process_region_eu.process_marketing_campaigns_eu ('Column' object is not callable; 37771)
[2025-06-11T16:16:51.473+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T16:16:51.502+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
