[2025-06-11T06:21:32.856+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaings manual__2025-06-11T06:20:26.872942+00:00 [queued]>
[2025-06-11T06:21:32.863+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaings manual__2025-06-11T06:20:26.872942+00:00 [queued]>
[2025-06-11T06:21:32.864+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-11T06:21:32.874+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ods_merge_group.merge_marketing_campaings> on 2025-06-11 06:20:26.872942+00:00
[2025-06-11T06:21:32.880+0000] {standard_task_runner.py:60} INFO - Started process 11679 to run task
[2025-06-11T06:21:32.882+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_ods_merge_v2', 'ods_merge_group.merge_marketing_campaings', 'manual__2025-06-11T06:20:26.872942+00:00', '--job-id', '1395', '--raw', '--subdir', 'DAGS_FOLDER/master_ods_dag.py', '--cfg-path', '/tmp/tmp7hddehlz']
[2025-06-11T06:21:32.883+0000] {standard_task_runner.py:88} INFO - Job 1395: Subtask ods_merge_group.merge_marketing_campaings
[2025-06-11T06:21:32.930+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaings manual__2025-06-11T06:20:26.872942+00:00 [running]> on host 590b48c4a67f
[2025-06-11T06:21:33.023+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_ods_merge_v2' AIRFLOW_CTX_TASK_ID='ods_merge_group.merge_marketing_campaings' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T06:20:26.872942+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T06:20:26.872942+00:00'
[2025-06-11T06:21:33.025+0000] {connection.py:486} INFO - Snowflake Connector for Python Version: 3.15.0, Python Version: 3.10.13, Platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.36
[2025-06-11T06:21:33.027+0000] {connection.py:1391} INFO - Connecting to GLOBAL Snowflake domain
[2025-06-11T06:21:34.626+0000] {logging_mixin.py:188} INFO - Successfully connected to Snowflake via snowflake.connector.
[2025-06-11T06:21:34.627+0000] {logging_mixin.py:188} INFO - Running merge for marketing_campaings...
[2025-06-11T06:21:34.627+0000] {logging_mixin.py:188} INFO - Error running merge for marketing_campaings: 'marketing_campaings'
[2025-06-11T06:21:35.278+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_ods_dag.py", line 171, in merge_table
    run_merge_query(t)
  File "/opt/airflow/dags/master_ods_dag.py", line 149, in run_merge_query
    merge_sql = MERGE_QUERIES[table_name]()
KeyError: 'marketing_campaings'
[2025-06-11T06:21:35.289+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=multi_region_ods_merge_v2, task_id=ods_merge_group.merge_marketing_campaings, execution_date=20250611T062026, start_date=20250611T062132, end_date=20250611T062135
[2025-06-11T06:21:35.300+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1395 for task ods_merge_group.merge_marketing_campaings ('marketing_campaings'; 11679)
[2025-06-11T06:21:35.341+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T06:21:35.358+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
