[2025-06-11T16:03:49.077+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_customers_eu manual__2025-06-11T16:03:34.479895+00:00 [queued]>
[2025-06-11T16:03:49.102+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_customers_eu manual__2025-06-11T16:03:34.479895+00:00 [queued]>
[2025-06-11T16:03:49.103+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-11T16:03:49.132+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_eu.process_customers_eu> on 2025-06-11 16:03:34.479895+00:00
[2025-06-11T16:03:49.148+0000] {standard_task_runner.py:60} INFO - Started process 16830 to run task
[2025-06-11T16:03:49.154+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_transform_staging_v2', 'process_region_eu.process_customers_eu', 'manual__2025-06-11T16:03:34.479895+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmp10vwqxav']
[2025-06-11T16:03:49.158+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask process_region_eu.process_customers_eu
[2025-06-11T16:03:49.290+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_transform_staging_v2.process_region_eu.process_customers_eu manual__2025-06-11T16:03:34.479895+00:00 [running]> on host 5950010ae7c1
[2025-06-11T16:03:49.524+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_transform_staging_v2' AIRFLOW_CTX_TASK_ID='process_region_eu.process_customers_eu' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T16:03:34.479895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T16:03:34.479895+00:00'
[2025-06-11T16:04:08.301+0000] {logging_mixin.py:188} INFO - Debugggg::::Vector(spark://5950010ae7c1:40801/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar, spark://5950010ae7c1:40801/jars/snowflake-jdbc-3.13.17.jar)
[2025-06-11T16:04:08.303+0000] {logging_mixin.py:188} INFO - Processing customers for region eu
[2025-06-11T16:04:08.362+0000] {logging_mixin.py:188} INFO - /opt/airflow/data/raw/region=eu/table=customers/load_date=2025-06-11
[2025-06-11T16:04:43.183+0000] {logging_mixin.py:188} INFO - Error processing customers for eu: transform_customers() takes 2 positional arguments but 3 were given
[2025-06-11T16:04:44.675+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_dag.py", line 242, in process_table
    df_transformed = transform_func(df_raw, region,exchange_rates)
TypeError: transform_customers() takes 2 positional arguments but 3 were given
[2025-06-11T16:04:44.720+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_region_transform_staging_v2, task_id=process_region_eu.process_customers_eu, execution_date=20250611T160334, start_date=20250611T160349, end_date=20250611T160444
[2025-06-11T16:04:44.767+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 162 for task process_region_eu.process_customers_eu (transform_customers() takes 2 positional arguments but 3 were given; 16830)
[2025-06-11T16:04:44.818+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T16:04:44.930+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
