[2025-06-08T17:15:47.211+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [queued]>
[2025-06-08T17:15:47.231+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [queued]>
[2025-06-08T17:15:47.231+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-08T17:15:47.267+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): run_transformation_asia> on 2025-06-07 01:00:00+00:00
[2025-06-08T17:15:47.281+0000] {standard_task_runner.py:60} INFO - Started process 65613 to run task
[2025-06-08T17:15:47.281+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-08T17:15:47.288+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'transform_cart_items', 'run_transformation_asia', 'scheduled__2025-06-07T01:00:00+00:00', '--job-id', '595', '--raw', '--subdir', 'DAGS_FOLDER/staging/cart_items_to_staging.py', '--cfg-path', '/tmp/tmpepvu7024']
[2025-06-08T17:15:47.290+0000] {standard_task_runner.py:88} INFO - Job 595: Subtask run_transformation_asia
[2025-06-08T17:15:47.330+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-08T17:15:47.438+0000] {task_command.py:423} INFO - Running <TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [running]> on host ca4d96b31043
[2025-06-08T17:15:47.711+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transform_cart_items' AIRFLOW_CTX_TASK_ID='run_transformation_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T01:00:00+00:00'
[2025-06-08T17:15:47.713+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/staging/cart_items_to_staging.py", line 86, in run_transformation_asia
    transform_cart_items(
TypeError: transform_cart_items() got an unexpected keyword argument 'table'
[2025-06-08T17:15:47.749+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=transform_cart_items, task_id=run_transformation_asia, execution_date=20250607T010000, start_date=20250608T171547, end_date=20250608T171547
[2025-06-08T17:15:47.784+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 595 for task run_transformation_asia (transform_cart_items() got an unexpected keyword argument 'table'; 65613)
[2025-06-08T17:15:47.823+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-08T17:15:47.910+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T19:31:48.984+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [queued]>
[2025-06-08T19:31:49.003+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [queued]>
[2025-06-08T19:31:49.004+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-08T19:31:49.036+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): run_transformation_asia> on 2025-06-07 01:00:00+00:00
[2025-06-08T19:31:49.048+0000] {standard_task_runner.py:60} INFO - Started process 40335 to run task
[2025-06-08T19:31:49.048+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-08T19:31:49.055+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'transform_cart_items', 'run_transformation_asia', 'scheduled__2025-06-07T01:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/staging/cart_items_to_staging.py', '--cfg-path', '/tmp/tmpc8vmvce0']
[2025-06-08T19:31:49.057+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask run_transformation_asia
[2025-06-08T19:31:49.148+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-08T19:31:49.237+0000] {task_command.py:423} INFO - Running <TaskInstance: transform_cart_items.run_transformation_asia scheduled__2025-06-07T01:00:00+00:00 [running]> on host 098d7b977cb8
[2025-06-08T19:31:49.446+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transform_cart_items' AIRFLOW_CTX_TASK_ID='run_transformation_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T01:00:00+00:00'
[2025-06-08T19:31:49.447+0000] {logging_mixin.py:188} INFO - Starting transformation for table: cart_items in region: asia
[2025-06-08T19:31:49.455+0000] {logging_mixin.py:188} INFO - Reading data from: /opt/airflow/data/raw/region=asia/table=cart_items/load_date=2025-06-08/
[2025-06-08T19:31:59.523+0000] {logging_mixin.py:188} INFO - [INFO] Processing 12 records for asia
[2025-06-08T19:32:00.040+0000] {logging_mixin.py:188} INFO - Sample transformed data for cart_items in asia:
[2025-06-08T19:32:04.421+0000] {logging_mixin.py:188} INFO - +------------+-------+----------+--------+--------------+-------------------+-------------------+-------+--------+
|cart_item_id|cart_id|variant_id|quantity|unit_price_jpy|added_at           |updated_at         |_region|_source |
+------------+-------+----------+--------+--------------+-------------------+-------------------+-------+--------+
|1           |1      |2         |1       |169800        |2024-03-15 09:35:20|2024-03-15 09:35:20|asia   |postgres|
|2           |1      |8         |2       |3500          |2024-03-15 09:40:35|2024-03-15 09:40:35|asia   |postgres|
|3           |2      |15        |1       |213000        |2024-03-16 11:20:10|2024-03-16 11:20:10|asia   |postgres|
|4           |3      |19        |1       |12800         |2024-03-17 13:25:45|2024-03-17 13:25:45|asia   |postgres|
|5           |4      |6         |1       |49800         |2024-03-18 15:45:30|2024-03-18 15:45:30|asia   |postgres|
+------------+-------+----------+--------+--------------+-------------------+-------------------+-------+--------+
only showing top 5 rows
[2025-06-08T19:32:04.422+0000] {logging_mixin.py:188} INFO - Writing transformed data to: /opt/airflow/data/staging/cart_items/region=asia/load_date=2025-06-08/
[2025-06-08T19:32:06.415+0000] {logging_mixin.py:188} INFO - Successfully transformed 12 records for cart_items in asia
[2025-06-08T20:00:43.347+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-06-08T20:00:43.399+0000] {process_utils.py:131} INFO - Sending 15 to group 40335. PIDs of all processes in the group: [40335]
[2025-06-08T20:00:43.402+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 40335
[2025-06-08T20:00:43.427+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-08T20:00:44.058+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=40335, status='terminated', exitcode=0, started='19:31:49') (40335) terminated with exit code 0
