[2025-06-11T16:06:47.824+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_marketing_campaigns_asia manual__2025-06-11T16:03:34.479895+00:00 [queued]>
[2025-06-11T16:06:47.844+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_marketing_campaigns_asia manual__2025-06-11T16:03:34.479895+00:00 [queued]>
[2025-06-11T16:06:47.844+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-11T16:06:47.879+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_asia.process_marketing_campaigns_asia> on 2025-06-11 16:03:34.479895+00:00
[2025-06-11T16:06:47.895+0000] {standard_task_runner.py:60} INFO - Started process 22060 to run task
[2025-06-11T16:06:47.902+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_transform_staging_v2', 'process_region_asia.process_marketing_campaigns_asia', 'manual__2025-06-11T16:03:34.479895+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmpd58qlqen']
[2025-06-11T16:06:47.907+0000] {standard_task_runner.py:88} INFO - Job 184: Subtask process_region_asia.process_marketing_campaigns_asia
[2025-06-11T16:06:48.061+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_marketing_campaigns_asia manual__2025-06-11T16:03:34.479895+00:00 [running]> on host 5950010ae7c1
[2025-06-11T16:06:48.366+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_transform_staging_v2' AIRFLOW_CTX_TASK_ID='process_region_asia.process_marketing_campaigns_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T16:03:34.479895+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T16:03:34.479895+00:00'
[2025-06-11T16:07:02.210+0000] {logging_mixin.py:188} INFO - Debugggg::::Vector(spark://5950010ae7c1:38357/jars/snowflake-jdbc-3.13.17.jar, spark://5950010ae7c1:38357/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar)
[2025-06-11T16:07:02.211+0000] {logging_mixin.py:188} INFO - Processing marketing_campaigns for region asia
[2025-06-11T16:07:02.244+0000] {logging_mixin.py:188} INFO - /opt/airflow/data/raw/region=asia/table=marketing_campaigns/load_date=2025-06-11
[2025-06-11T16:07:22.182+0000] {logging_mixin.py:188} INFO - Error processing marketing_campaigns for asia: 'Column' object is not callable
[2025-06-11T16:07:23.563+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_dag.py", line 242, in process_table
    df_transformed = transform_func(df_raw, region,exchange_rates)
  File "/opt/airflow/scripts/etl/transform/marketing_campaigns.py", line 93, in transform_marketing_campaigns
    return transform_marketing_campaigns_asia(df, exchange_rates)
  File "/opt/airflow/scripts/etl/transform/marketing_campaigns.py", line 43, in transform_marketing_campaigns_asia
    (col("budget_jpy").lit(rate)).alias("budget_usd"),  # normalize to float
TypeError: 'Column' object is not callable
[2025-06-11T16:07:23.585+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=multi_region_transform_staging_v2, task_id=process_region_asia.process_marketing_campaigns_asia, execution_date=20250611T160334, start_date=20250611T160647, end_date=20250611T160723
[2025-06-11T16:07:23.611+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 184 for task process_region_asia.process_marketing_campaigns_asia ('Column' object is not callable; 22060)
[2025-06-11T16:07:23.635+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T16:07:23.675+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
