[2025-06-04T20:37:07.150+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schema_evolution_framework.run_schema_evolution manual__2025-06-04T20:37:02+00:00 [queued]>
[2025-06-04T20:37:07.161+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schema_evolution_framework.run_schema_evolution manual__2025-06-04T20:37:02+00:00 [queued]>
[2025-06-04T20:37:07.161+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-04T20:37:07.176+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_schema_evolution> on 2025-06-04 20:37:02+00:00
[2025-06-04T20:37:07.181+0000] {standard_task_runner.py:60} INFO - Started process 8357 to run task
[2025-06-04T20:37:07.183+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'schema_evolution_framework', 'run_schema_evolution', 'manual__2025-06-04T20:37:02+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/schema_drift/schema_drift.py', '--cfg-path', '/tmp/tmpmsa3_kj9']
[2025-06-04T20:37:07.185+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask run_schema_evolution
[2025-06-04T20:37:07.207+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-04T20:37:07.250+0000] {task_command.py:423} INFO - Running <TaskInstance: schema_evolution_framework.run_schema_evolution manual__2025-06-04T20:37:02+00:00 [running]> on host d21a88c59131
[2025-06-04T20:37:07.351+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='schema_evolution_framework' AIRFLOW_CTX_TASK_ID='run_schema_evolution' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T20:37:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T20:37:02+00:00'
[2025-06-04T20:37:07.351+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-04T20:37:07.352+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/pyspark_jobs/schema_evolution.py --region asia --table customers --load_date 2025-06-04']
[2025-06-04T20:37:07.360+0000] {subprocess.py:86} INFO - Output:
[2025-06-04T20:37:08.930+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/pyspark_jobs/schema_evolution.py", line 251
[2025-06-04T20:37:08.930+0000] {subprocess.py:93} INFO -     Example usage
[2025-06-04T20:37:08.931+0000] {subprocess.py:93} INFO -             ^^^^^
[2025-06-04T20:37:08.931+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2025-06-04T20:37:08.945+0000] {subprocess.py:93} INFO - 25/06/04 20:37:08 INFO ShutdownHookManager: Shutdown hook called
[2025-06-04T20:37:08.948+0000] {subprocess.py:93} INFO - 25/06/04 20:37:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-1af66757-3880-493c-9eed-068b818f1282
[2025-06-04T20:37:08.985+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-04T20:37:09.000+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-04T20:37:09.004+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=schema_evolution_framework, task_id=run_schema_evolution, execution_date=20250604T203702, start_date=20250604T203707, end_date=20250604T203709
[2025-06-04T20:37:09.017+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task run_schema_evolution (Bash command failed. The command returned a non-zero exit code 1.; 8357)
[2025-06-04T20:37:09.041+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T20:37:09.091+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
